In [9]:
# 모둘 로드
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

In [10]:
# 데이터 불러오기
df=pd.read_excel('../data/시군구별 요양기관 현황(가공데이터).xlsx')
df

,C0,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C70,C71,C72,C73,C74,C75,C76,C77,C78,C79
0,2008,전국,49540367,62.2,62.1,63.6,63.3,80.7,63.1,62.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2008,서울특별시,10200827,62.2,62.1,63.6,63.3,80.7,63.1,62.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2008,부산광역시,3564577,62.2,62.1,63.6,63.3,80.7,63.1,62.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2008,대구광역시,2492724,62.2,62.1,63.6,63.3,80.7,63.1,62.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2008,인천광역시,2692696,62.2,62.1,63.6,63.3,80.7,63.1,62.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,2023,전북특별자치도,1754757,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,3.0,604.0,0.0,35.0,502.0,4.0,11.0,148.0,240.0,986.0
280,2023,전라남도,1804217,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,6.0,513.0,0.0,28.0,356.0,3.0,19.0,216.0,327.0,849.0
281,2023,경상북도,2554324,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,11.0,696.0,1.0,8.0,618.0,2.0,22.0,216.0,298.0,1095.0
282,2023,경상남도,3251158,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,22.0,944.0,1.0,24.0,781.0,1.0,20.0,173.0,220.0,1372.0
283,2023,제주특별자치도,675252,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,1.0,244.0,1.0,1.0,196.0,0.0,6.0,11.0,48.0,321.0

In [11]:
# 결측치 많은 2008년도 데이터 삭제
df2 = df[df['C0'] != 2008]
df2

,C0,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C70,C71,C72,C73,C74,C75,C76,C77,C78,C79
17,2009,전국,49773145,63.4,63.4,65.8,65.6,88.2,64.5,63.7,...,183.0,14242.0,49.0,158.0,11782.0,17.0,239.0,1292.0,1914.0,21015.0
18,2009,서울특별시,10208302,63.4,63.4,65.8,65.6,88.2,64.5,63.7,...,69.0,4395.0,6.0,29.0,3313.0,0.0,25.0,1.0,0.0,5289.0
19,2009,부산광역시,3543030,63.4,63.4,65.8,65.6,88.2,64.5,63.7,...,9.0,1025.0,13.0,7.0,958.0,0.0,16.0,10.0,5.0,1530.0
20,2009,대구광역시,2489781,63.4,63.4,65.8,65.6,88.2,64.5,63.7,...,17.0,709.0,1.0,8.0,734.0,0.0,8.0,9.0,9.0,1171.0
21,2009,인천광역시,2710579,63.4,63.4,65.8,65.6,88.2,64.5,63.7,...,3.0,676.0,1.0,12.0,502.0,0.0,10.0,23.0,24.0,980.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,2023,전북특별자치도,1754757,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,3.0,604.0,0.0,35.0,502.0,4.0,11.0,148.0,240.0,986.0
280,2023,전라남도,1804217,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,6.0,513.0,0.0,28.0,356.0,3.0,19.0,216.0,327.0,849.0
281,2023,경상북도,2554324,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,11.0,696.0,1.0,8.0,618.0,2.0,22.0,216.0,298.0,1095.0
282,2023,경상남도,3251158,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,22.0,944.0,1.0,24.0,781.0,1.0,20.0,173.0,220.0,1372.0
283,2023,제주특별자치도,675252,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,1.0,244.0,1.0,1.0,196.0,0.0,6.0,11.0,48.0,321.0

In [12]:
# 결측치 많은 C18, C68 열 삭제

df3=df2.drop(columns=['C16','C18','C68'])
df3

,C0,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C70,C71,C72,C73,C74,C75,C76,C77,C78,C79
17,2009,전국,49773145,63.4,63.4,65.8,65.6,88.2,64.5,63.7,...,183.0,14242.0,49.0,158.0,11782.0,17.0,239.0,1292.0,1914.0,21015.0
18,2009,서울특별시,10208302,63.4,63.4,65.8,65.6,88.2,64.5,63.7,...,69.0,4395.0,6.0,29.0,3313.0,0.0,25.0,1.0,0.0,5289.0
19,2009,부산광역시,3543030,63.4,63.4,65.8,65.6,88.2,64.5,63.7,...,9.0,1025.0,13.0,7.0,958.0,0.0,16.0,10.0,5.0,1530.0
20,2009,대구광역시,2489781,63.4,63.4,65.8,65.6,88.2,64.5,63.7,...,17.0,709.0,1.0,8.0,734.0,0.0,8.0,9.0,9.0,1171.0
21,2009,인천광역시,2710579,63.4,63.4,65.8,65.6,88.2,64.5,63.7,...,3.0,676.0,1.0,12.0,502.0,0.0,10.0,23.0,24.0,980.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,2023,전북특별자치도,1754757,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,3.0,604.0,0.0,35.0,502.0,4.0,11.0,148.0,240.0,986.0
280,2023,전라남도,1804217,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,6.0,513.0,0.0,28.0,356.0,3.0,19.0,216.0,327.0,849.0
281,2023,경상북도,2554324,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,11.0,696.0,1.0,8.0,618.0,2.0,22.0,216.0,298.0,1095.0
282,2023,경상남도,3251158,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,22.0,944.0,1.0,24.0,781.0,1.0,20.0,173.0,220.0,1372.0
283,2023,제주특별자치도,675252,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,1.0,244.0,1.0,1.0,196.0,0.0,6.0,11.0,48.0,321.0

In [13]:
# C1 기준으로 지정된 순서 설정
custom_order = [
    '전국', '서울특별시', '부산광역시', '대구광역시', '인천광역시', '광주광역시',
    '대전광역시', '울산광역시', '세종특별자치시', '경기도', '강원특별자치도',
    '충청북도', '충청남도', '전북특별자치도', '전라남도', '경상북도', '경상남도',
    '제주특별자치도'
]

df3['C1'] = pd.Categorical(df3['C1'], categories=custom_order, ordered=True)

# C1을 지정된 순서로, C0을 오름차순으로 정렬
df3 = df3.sort_values(by=['C1', 'C0'])
df3

,C0,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C70,C71,C72,C73,C74,C75,C76,C77,C78,C79
17,2009,전국,49773145,63.4,63.4,65.8,65.6,88.2,64.5,63.7,...,183.0,14242.0,49.0,158.0,11782.0,17.0,239.0,1292.0,1914.0,21015.0
34,2010,전국,50515666,64.3,65.3,67.7,66.8,93.5,65.7,64.8,...,191.0,14681.0,46.0,168.0,12061.0,17.0,240.0,1296.0,1916.0,21096.0
51,2011,전국,50734284,64.9,66.6,70.1,68.8,100.0,67.1,66.4,...,199.0,15058.0,40.0,184.0,12401.0,17.0,240.0,1294.0,1917.0,21079.0
68,2012,전국,50948272,66.0,68.5,71.9,70.6,104.2,68.8,67.7,...,201.0,15365.0,33.0,201.0,12705.0,15.0,243.0,1301.0,1910.0,20958.0
86,2013,전국,51141463,67.5,70.1,73.8,72.5,106.9,70.8,69.1,...,203.0,15727.0,34.0,212.0,13100.0,15.0,243.0,1307.0,1905.0,20890.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,2019,제주특별자치도,670989,74.9,83.4,84.8,84.8,130.1,85.0,81.5,...,1.0,218.0,1.0,0.0,193.0,0.0,6.0,11.0,47.0,297.0
229,2020,제주특별자치도,674635,76.2,85.8,87.4,87.3,135.2,88.0,83.8,...,1.0,219.0,1.0,1.0,194.0,0.0,6.0,11.0,48.0,303.0
247,2021,제주특별자치도,676759,77.3,87.6,88.7,89.8,140.3,90.9,86.1,...,1.0,229.0,1.0,1.0,195.0,0.0,6.0,11.0,48.0,305.0
265,2022,제주특별자치도,678159,78.4,90.2,90.7,92.6,146.1,94.2,88.5,...,1.0,244.0,1.0,1.0,194.0,0.0,6.0,11.0,48.0,318.0
283,2023,제주특별자치도,675252,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,1.0,244.0,1.0,1.0,196.0,0.0,6.0,11.0,48.0,321.0

In [14]:
df3.loc[df3['C1'] == '세종특별자치시']

,C0,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C70,C71,C72,C73,C74,C75,C76,C77,C78,C79
76,2012,세종특별자치시,113117,66.0,68.5,71.9,70.6,104.2,68.8,67.7,...,0.0,20.0,0.0,0.0,21.0,0.0,1.0,9.0,6.0,51.0
94,2013,세종특별자치시,122153,67.5,70.1,73.8,72.5,106.9,70.8,69.1,...,0.0,24.0,0.0,0.0,26.0,0.0,1.0,9.0,6.0,56.0
112,2014,세종특별자치시,156125,68.8,72.2,75.8,74.4,110.0,72.8,71.0,...,0.0,36.0,0.0,0.0,32.0,0.0,1.0,11.0,6.0,67.0
130,2015,세종특별자치시,210884,70.0,74.4,77.5,76.0,113.5,75.1,73.1,...,0.0,51.0,0.0,0.0,40.0,0.0,1.0,11.0,7.0,81.0
148,2016,세종특별자치시,243048,71.0,76.6,79.0,77.7,117.1,77.4,74.9,...,0.0,60.0,0.0,0.0,53.0,0.0,1.0,11.0,7.0,89.0
166,2017,세종특별자치시,280100,72.3,79.0,80.9,80.0,121.4,80.1,77.1,...,1.0,72.0,0.0,0.0,65.0,0.0,1.0,10.0,7.0,104.0
184,2018,세종특별자치시,314126,73.5,81.4,83.1,82.3,125.5,82.4,79.3,...,1.0,80.0,0.0,1.0,73.0,0.0,1.0,10.0,7.0,115.0
202,2019,세종특별자치시,340575,74.9,83.4,84.8,84.8,130.1,85.0,81.5,...,1.0,85.0,0.0,1.0,76.0,0.0,1.0,10.0,7.0,122.0
220,2020,세종특별자치시,355831,76.2,85.8,87.4,87.3,135.2,88.0,83.8,...,1.0,91.0,0.0,4.0,82.0,0.0,1.0,10.0,7.0,143.0
238,2021,세종특별자치시,371895,77.3,87.6,88.7,89.8,140.3,90.9,86.1,...,1.0,96.0,0.0,3.0,82.0,0.0,1.0,10.0,7.0,151.0
256,2022,세종특별자치시,383591,78.4,90.2,90.7,92.6,146.1,94.2,88.5,...,1.0,98.0,0.0,4.0,88.0,0.0,1.0,10.0,7.0,157.0
274,2023,세종특별자치시,386525,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,1.0,99.0,0.0,4.0,97.0,0.0,1.0,10.0,7.0,161.0

In [15]:
# C1이 '세종특별자치시'인 행의 C50~C61 열을 선형 보간
cols_to_interpolate = ['C50', 'C51', 'C52', 'C53', 'C54', 'C55', 'C56', 'C57', 'C58', 'C59', 'C60', 'C61']
df3.loc[df3['C1'] == '세종특별자치시', cols_to_interpolate] = df3.loc[df3['C1'] == '세종특별자치시', cols_to_interpolate].interpolate(method='linear', axis=0)

In [16]:
df3.loc[df3['C1'] == '세종특별자치시']

,C0,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C70,C71,C72,C73,C74,C75,C76,C77,C78,C79
76,2012,세종특별자치시,113117,66.0,68.5,71.9,70.6,104.2,68.8,67.7,...,0.0,20.0,0.0,0.0,21.0,0.0,1.0,9.0,6.0,51.0
94,2013,세종특별자치시,122153,67.5,70.1,73.8,72.5,106.9,70.8,69.1,...,0.0,24.0,0.0,0.0,26.0,0.0,1.0,9.0,6.0,56.0
112,2014,세종특별자치시,156125,68.8,72.2,75.8,74.4,110.0,72.8,71.0,...,0.0,36.0,0.0,0.0,32.0,0.0,1.0,11.0,6.0,67.0
130,2015,세종특별자치시,210884,70.0,74.4,77.5,76.0,113.5,75.1,73.1,...,0.0,51.0,0.0,0.0,40.0,0.0,1.0,11.0,7.0,81.0
148,2016,세종특별자치시,243048,71.0,76.6,79.0,77.7,117.1,77.4,74.9,...,0.0,60.0,0.0,0.0,53.0,0.0,1.0,11.0,7.0,89.0
166,2017,세종특별자치시,280100,72.3,79.0,80.9,80.0,121.4,80.1,77.1,...,1.0,72.0,0.0,0.0,65.0,0.0,1.0,10.0,7.0,104.0
184,2018,세종특별자치시,314126,73.5,81.4,83.1,82.3,125.5,82.4,79.3,...,1.0,80.0,0.0,1.0,73.0,0.0,1.0,10.0,7.0,115.0
202,2019,세종특별자치시,340575,74.9,83.4,84.8,84.8,130.1,85.0,81.5,...,1.0,85.0,0.0,1.0,76.0,0.0,1.0,10.0,7.0,122.0
220,2020,세종특별자치시,355831,76.2,85.8,87.4,87.3,135.2,88.0,83.8,...,1.0,91.0,0.0,4.0,82.0,0.0,1.0,10.0,7.0,143.0
238,2021,세종특별자치시,371895,77.3,87.6,88.7,89.8,140.3,90.9,86.1,...,1.0,96.0,0.0,3.0,82.0,0.0,1.0,10.0,7.0,151.0
256,2022,세종특별자치시,383591,78.4,90.2,90.7,92.6,146.1,94.2,88.5,...,1.0,98.0,0.0,4.0,88.0,0.0,1.0,10.0,7.0,157.0
274,2023,세종특별자치시,386525,79.7,92.1,93.0,95.4,151.9,97.6,91.0,...,1.0,99.0,0.0,4.0,97.0,0.0,1.0,10.0,7.0,161.0

In [65]:
# C1이 '세종특별자치시'인 행의 C50~C61 KNN 알고리즘으로 결측치 채우기


cols_to_impute = ['C50', 'C51', 'C52', 'C53', 'C54', 'C55', 'C56', 'C57', 'C58', 'C59', 'C60', 'C61']
# '-' 값을 NaN으로 변환
df3[cols_to_impute] = df3[cols_to_impute].replace('-', np.nan)

# KNNImputer 객체 생성
imputer = KNNImputer(n_neighbors=5)

# '세종특별자치시'인 행에서 특정 열의 결측치를 KNN으로 채우기
df3.loc[df3['C1'] == '세종특별자치시', cols_to_impute] = imputer.fit_transform(df3.loc[df3['C1'] == '세종특별자치시', cols_to_impute])

In [66]:
# 나머지 결측치 0으로 채우기

# '-' 값을 NaN으로 변환
df3 = df3.replace('-', np.nan)
df3.loc[:, df3.columns.difference(['C0', 'C1'])] = df3.loc[:, df3.columns.difference(['C0', 'C1'])].fillna(0)

In [67]:
df3.isna().sum()

C0     0
C1     0
C2     0
C3     0
C4     0
      ..
C75    0
C76    0
C77    0
C78    0
C79    0
Length: 77, dtype: int64

In [68]:
# DataFrame -> excel
df3.to_excel("preprocessing.xlsx",index=False)

In [69]:
#C1 컬럼 원핫 인코딩
df3 = pd.get_dummies(df3, columns=['C1'], drop_first=True)

In [70]:
# DataFrame -> excel
df3.to_excel("preprocessing_onehot.xlsx",index=False)